### PR TITLE
Fixed memory leak in zmq::z85_decode

### LINKED ISSUE #387: Memory leak in test `test_z85`
I've been experimenting with a version of [Miri](https://github.com/rust-lang/miri) that can execute foreign functions by interpreting the LLVM bytecode that is produced during a crate's build process. We're hoping that our results can assist with the [Krabcake](https://github.com/pnkfelix/krabcake) project.

Miri reports the following memory leak when executing the test `test_z85`:
```
error: memory leaked: alloc24744 (Rust heap, size: 41, align: 1), allocated here:
    --> .../rust/library/alloc/src/alloc.rs:98:9
     |
98   |         __rust_alloc(layout.size(), layout.align())
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: inside `std::alloc::alloc` at .../rust/library/alloc/src/alloc.rs:98:9: 98:52
     = note: inside `std::alloc::Global::alloc_impl` at .../rust/library/alloc/src/alloc.rs:181:73: 181:86
     = note: inside `<std::alloc::Global as std::alloc::Allocator>::allocate` at .../rust/library/alloc/src/alloc.rs:241:9: 241:39
     = note: inside `alloc::raw_vec::RawVec::<u8>::allocate_in` at .../rust/library/alloc/src/raw_vec.rs:184:45: 184:67
     = note: inside `alloc::raw_vec::RawVec::<u8>::with_capacity_in` at .../rust/library/alloc/src/raw_vec.rs:130:9: 130:69
     = note: inside `std::vec::Vec::<u8>::with_capacity_in` at .../rust/library/alloc/src/vec/mod.rs:670:20: 670:61
     = note: inside `std::vec::Vec::<u8>::with_capacity` at .../rust/library/alloc/src/vec/mod.rs:479:9: 479:49
     = note: inside `std::ffi::CString::new::spec_new_impl_bytes` at .../rust/library/alloc/src/ffi/c_str.rs:287:30: 287:58
     = note: inside `<&str as std::ffi::CString::new::SpecNewImpl>::spec_new_impl` at .../rust/library/alloc/src/ffi/c_str.rs:306:17: 306:53
     = note: inside `std::ffi::CString::new::<&str>` at .../rust/library/alloc/src/ffi/c_str.rs:316:9: 316:26
note: inside `zmq::z85_decode`
    --> /home/icmccorm/git/investigation/zmq/src/lib.rs:1343:17
     |
1343 |     let c_str = ffi::CString::new(data)?;
     |                 ^^^^^^^^^^^^^^^^^^^^^^^
note: inside `test_z85`
    --> tests/z85.rs:10:19
     |
10   |     let decoded = z85_decode(test_str).unwrap();
     |                   ^^^^^^^^^^^^^^^^^^^^
```
It appears that this is caused by the use of `CString::into_raw` on line 1346 of [src/lib.rs](url)
```
    unsafe {
        zmq_sys::zmq_z85_decode(dest.as_mut_ptr(), c_str.into_raw());
    }
```
Since this pointer is never re-wrapped using `CString::from_raw`, the underlying memory is leaked.

### PR DESCRIPTION
**Pull request by icmccorm**
Fixes #387

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -1341,9 +1341,11 @@ pub fn z85_decode(data: &str) -> result::Result<Vec<u8>, DecodeError> {
     let mut dest = vec![0u8; len];
 
     let c_str = ffi::CString::new(data)?;
+    let c_str_ptr = c_str.into_raw();
 
     unsafe {
-        zmq_sys::zmq_z85_decode(dest.as_mut_ptr(), c_str.into_raw());
+        zmq_sys::zmq_z85_decode(dest.as_mut_ptr(), c_str_ptr);
+        drop(ffi::CString::from_raw(c_str_ptr));
```
Comment (MarijnS95) [inline src/lib.rs:1348]: Any reason for not simply using https://doc.rust-lang.org/std/ffi/struct.CString.html#method.as_ptr, and remove `into_raw`/`from_raw` altogether?

Besides, the `drop()` here is superfluous.

**Review by MarijnS95 — COMMENTED** [review]
Thanks for fixing the title already! To make this PR even more convenient to merge, can you change the description to `Fixes #387` so that GitHub automatically closes it upon merge? Thanks!

File: src/lib.rs (hunk 1 above)
Comment (icmccorm) [reply src/lib.rs:1348]: Good point—I'll update to use `as_ptr`.
